import json
import pathlib
import re
from typing import Iterable, List, Tuple

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXAMPLES_DIR = ROOT / "data" / "raw_scripts" / "AHK_v2_Examples"
OUTPUT_JSONL = ROOT / "data" / "ahk_example_metadata.jsonl"
PREVIEW_MD = ROOT / "docs" / "AHK_Example_Metadata_Preview.md"

HOTKEY_PATTERN = re.compile(r"^\s*([^\s;].*?)::")
FUNCTION_PATTERN = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(.*\)\s*{")
CONTROL_KEYWORDS = {
    "if",
    "else",
    "while",
    "for",
    "loop",
    "try",
    "catch",
    "finally",
    "switch",
    "case",
    "default",
    "return",
    "break",
    "continue",
}


def iter_header(lines: Iterable[str]) -> Tuple[str, List[str], List[str]]:
    """Capture directives and leading comment lines before code starts."""

    title = ""
    comment_lines: List[str] = []
    directives: List[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("#"):
            directives.append(stripped)
            continue
        if stripped.startswith(";"):
            text = stripped.lstrip(";").strip()
            if text:
                if not title:
                    title = text
                comment_lines.append(text)
            continue
        # Stop at the first non-comment, non-directive content
        break

    return title, comment_lines, directives


def read_snippet(lines: list[str], max_chars: int = 800) -> str:
    snippet = "".join(lines[:40]).strip()
    if len(snippet) > max_chars:
        snippet = snippet[: max_chars - 3].rstrip() + "..."
    return snippet


def detect_hotkeys(lines: list[str]) -> list[str]:
    hotkeys = []
    for line in lines:
        if line.strip().startswith(";"):
            continue
        match = HOTKEY_PATTERN.match(line)
        if match:
            hotkeys.append(match.group(1).strip())
    return hotkeys


def detect_functions(lines: list[str]) -> list[str]:
    functions = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith(";") or stripped.startswith("#"):
            continue
        keyword = stripped.split()[0].lower()
        if keyword.rstrip("(") in CONTROL_KEYWORDS:
            continue
        match = FUNCTION_PATTERN.match(stripped)
        if match:
            functions.append(match.group(1))
    return functions


def main() -> None:
    example_paths = sorted(EXAMPLES_DIR.glob("*.ahk"))
    records = []

    for path in example_paths:
        raw_lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        title, comment_lines, directives = iter_header(raw_lines)
        hotkeys = detect_hotkeys(raw_lines)
        functions = detect_functions(raw_lines)
        name_parts = path.stem.split("_")
        record = {
            "file": path.name,
            "group": name_parts[0],
            "category": "_".join(name_parts[:2]) if len(name_parts) > 1 else name_parts[0],
            "title": title,
            "description": " ".join(comment_lines),
            "comment_lines": comment_lines,
            "directives": directives,
            "hotkeys": hotkeys,
            "functions": functions,
            "line_count": len(raw_lines),
            "snippet": read_snippet(raw_lines),
            "relative_path": str(path.relative_to(ROOT)),
        }
        records.append(record)

    # Write JSONL for downstream processing
    OUTPUT_JSONL.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n",
        encoding="utf-8",
    )

    # Create a small preview table in Markdown
    preview_rows = records[:25]
    header = "| File | Category | Title | Hotkeys | Functions |\n| --- | --- | --- | --- | --- |\n"
    body = "\n".join(
        f"| {row['file']} | {row['category']} | {row['title'] or '—'} | {len(row['hotkeys'])} | {len(row['functions'])} |"
        for row in preview_rows
    )
    PREVIEW_MD.write_text(
        "# AutoHotkey v2 Example Metadata Preview\n\n"
        "This file is auto-generated by `scripts/scrape_example_metadata.py` and shows the first 25 examples with derived \n"
        "titles plus counts of detected hotkeys and function definitions. The full dataset lives in `data/ahk_example_metadata.jsonl`.\n\n"
        + header
        + body
        + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
