import json
import pathlib
from typing import Iterable

ROOT = pathlib.Path(__file__).resolve().parents[1]
EXAMPLES_DIR = ROOT / "data" / "raw_scripts" / "AHK_v2_Examples"
OUTPUT_JSONL = ROOT / "data" / "ahk_example_metadata.jsonl"
PREVIEW_MD = ROOT / "docs" / "AHK_Example_Metadata_Preview.md"


def iter_comment_block(lines: Iterable[str]):
    title = ""
    collected = []
    for line in lines:
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            # Skip blank lines and directives
            continue
        if stripped.startswith(";"):
            text = stripped.lstrip(";").strip()
            if text:
                if not title:
                    title = text
                collected.append(text)
            continue
        # Stop at the first non-comment, non-directive content
        break
    return title, collected


def read_snippet(lines: list[str], max_chars: int = 800) -> str:
    snippet = "".join(lines[:40]).strip()
    if len(snippet) > max_chars:
        snippet = snippet[: max_chars - 3].rstrip() + "..."
    return snippet


def main() -> None:
    example_paths = sorted(EXAMPLES_DIR.glob("*.ahk"))
    records = []

    for path in example_paths:
        raw_lines = path.read_text(encoding="utf-8", errors="ignore").splitlines()
        title, description_lines = iter_comment_block(raw_lines)
        record = {
            "file": path.name,
            "group": path.stem.split("_")[0],
            "title": title,
            "description": " ".join(description_lines),
            "snippet": read_snippet(raw_lines),
            "relative_path": str(path.relative_to(ROOT)),
        }
        records.append(record)

    # Write JSONL for downstream processing
    OUTPUT_JSONL.write_text(
        "\n".join(json.dumps(r, ensure_ascii=False) for r in records) + "\n",
        encoding="utf-8",
    )

    # Create a small preview table in Markdown
    preview_rows = records[:25]
    header = "| File | Group | Title |\n| --- | --- | --- |\n"
    body = "\n".join(
        f"| {row['file']} | {row['group']} | {row['title'] or '—'} |" for row in preview_rows
    )
    PREVIEW_MD.write_text(
        "# AutoHotkey v2 Example Metadata Preview\n\n"
        "This file is auto-generated by `scripts/scrape_example_metadata.py` and shows the first 25 examples with their \n"
        "derived titles. The full dataset lives in `data/ahk_example_metadata.jsonl`.\n\n" + header + body + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
